function duel() {
  return {
    worldMap: [
      [
        'HEADQUARTERS',
        'PLAIN',
        'CITY',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'MOUNTAIN',
        'MOUNTAIN',
      ],
      [
        'PLAIN',
        'BASE',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'MOUNTAIN',
      ],
      [
        'CITY',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'PLAIN',
        'FOREST',
        'FOREST',
        'RIVER',
        'RIVER',
      ],
      [
        'PLAIN',
        'PLAIN',
        'ROAD',
        'CITY',
        'ROAD',
        'ROAD',
        'ROAD',
        'FOREST',
        'PLAIN',
        'PLAIN',
      ],
      [
        'PLAIN',
        'PLAIN',
        'ROAD',
        'ROAD',
        'ROAD',
        'CITY',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
      ],
      [
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'CITY',
        'ROAD',
        'ROAD',
        'ROAD',
        'PLAIN',
        'PLAIN',
      ],
      [
        'PLAIN',
        'PLAIN',
        'FOREST',
        'ROAD',
        'ROAD',
        'ROAD',
        'CITY',
        'ROAD',
        'PLAIN',
        'PLAIN',
      ],
      [
        'RIVER',
        'RIVER',
        'FOREST',
        'FOREST',
        'PLAIN',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'CITY',
      ],
      [
        'MOUNTAIN',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'BASE',
        'PLAIN',
      ],
      [
        'MOUNTAIN',
        'MOUNTAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'CITY',
        'PLAIN',
        'HEADQUARTERS',
      ],
    ],
    factions: [
      {
        id: 'BLUE',
        type: 'COMPUTER',
        team: 1,
      },
      {
        id: 'RED',
        type: 'HUMAN',
        team: 2,
      },
    ],
    buildings: [
      {
        type: 'HEADQUARTERS',
        factionId: 'BLUE',
        position: {
          x: 0,
          y: 0,
        },
      },
      {
        type: 'HEADQUARTERS',
        factionId: 'RED',
        position: {
          x: 9,
          y: 9,
        },
      },
      {
        type: 'BASE',
        factionId: 'RED',
        position: {
          x: 8,
          y: 8,
        },
      },
      {
        type: 'CITY',
        factionId: 'RED',
        position: {
          x: 9,
          y: 7,
        },
      },
      {
        type: 'CITY',
        factionId: 'RED',
        position: {
          x: 7,
          y: 9,
        },
      },
      {
        type: 'BASE',
        factionId: 'BLUE',
        position: {
          x: 1,
          y: 1,
        },
      },
      {
        type: 'CITY',
        factionId: 'BLUE',
        position: {
          x: 2,
          y: 0,
        },
      },
      {
        type: 'CITY',
        factionId: 'BLUE',
        position: {
          x: 0,
          y: 2,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 5,
          y: 4,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 4,
          y: 5,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 3,
          y: 3,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 6,
          y: 6,
        },
      },
    ],
    units: [
    ],
    name: 'Duel',
    description: 'A duel',
  }
}

export default duel
