function townMayhem() {
  return {
    worldMap: [
      [
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'MOUNTAIN',
        'MOUNTAIN',
        'MOUNTAIN',
        'RIVER',
        'MOUNTAIN',
        'MOUNTAIN',
        'MOUNTAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
      ],
      [
        'HEADQUARTERS',
        'CITY',
        'BASE',
        'AIRPORT',
        'PLAIN',
        'PLAIN',
        'FOREST',
        'FOREST',
        'BASE',
        'RIVER',
        'BASE',
        'FOREST',
        'FOREST',
        'PLAIN',
        'PLAIN',
        'AIRPORT',
        'BASE',
        'CITY',
        'HEADQUARTERS',
      ],
      [
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
      ],
      [
        'MOUNTAIN',
        'PLAIN',
        'ROAD',
        'CITY',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'CITY',
        'RIVER',
        'CITY',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'CITY',
        'ROAD',
        'PLAIN',
        'MOUNTAIN',
      ],
      [
        'MOUNTAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'FOREST',
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
        'FOREST',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'MOUNTAIN',
      ],
      [
        'MOUNTAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'FOREST',
        'RIVER',
        'BASE',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'BASE',
        'RIVER',
        'FOREST',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'MOUNTAIN',
      ],
      [
        'CITY',
        'PLAIN',
        'ROAD',
        'BASE',
        'CITY',
        'RIVER',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'CITY',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'RIVER',
        'CITY',
        'BASE',
        'ROAD',
        'PLAIN',
        'CITY',
      ],
      [
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
        'RIVER',
        'PLAIN',
        'ROAD',
        'CITY',
        'AIRPORT',
        'CITY',
        'ROAD',
        'PLAIN',
        'RIVER',
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
      ],
      [
        'CITY',
        'PLAIN',
        'ROAD',
        'BASE',
        'CITY',
        'RIVER',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'CITY',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'RIVER',
        'CITY',
        'BASE',
        'ROAD',
        'PLAIN',
        'CITY',
      ],
      [
        'MOUNTAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'FOREST',
        'RIVER',
        'BASE',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'BASE',
        'RIVER',
        'FOREST',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'MOUNTAIN',
      ],
      [
        'MOUNTAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'FOREST',
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
        'FOREST',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'MOUNTAIN',
      ],
      [
        'MOUNTAIN',
        'PLAIN',
        'ROAD',
        'CITY',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'CITY',
        'RIVER',
        'CITY',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'CITY',
        'ROAD',
        'PLAIN',
        'MOUNTAIN',
      ],
      [
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
      ],
      [
        'HEADQUARTERS',
        'CITY',
        'BASE',
        'AIRPORT',
        'PLAIN',
        'PLAIN',
        'FOREST',
        'FOREST',
        'BASE',
        'RIVER',
        'BASE',
        'FOREST',
        'FOREST',
        'PLAIN',
        'PLAIN',
        'AIRPORT',
        'BASE',
        'CITY',
        'HEADQUARTERS',
      ],
      [
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'MOUNTAIN',
        'MOUNTAIN',
        'MOUNTAIN',
        'RIVER',
        'MOUNTAIN',
        'MOUNTAIN',
        'MOUNTAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
      ],
    ],
    factions: [
      {
        id: 'RED',
        type: 'COMPUTER',
        team: 1,
      },
      {
        id: 'BLUE',
        type: 'COMPUTER',
        team: 2,
      },
      {
        id: 'YELLOW',
        type: 'COMPUTER',
        team: 3,
      },
      {
        id: 'GREEN',
        type: 'COMPUTER',
        team: 4,
      },
    ],
    buildings: [
      {
        type: 'HEADQUARTERS',
        factionId: 'RED',
        position: {
          x: 0,
          y: 1,
        },
      },
      {
        type: 'HEADQUARTERS',
        factionId: 'BLUE',
        position: {
          x: 18,
          y: 1,
        },
      },
      {
        type: 'HEADQUARTERS',
        factionId: 'YELLOW',
        position: {
          x: 18,
          y: 13,
        },
      },
      {
        type: 'HEADQUARTERS',
        factionId: 'GREEN',
        position: {
          x: 0,
          y: 13,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 15,
          y: 11,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 3,
          y: 11,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 3,
          y: 3,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 15,
          y: 3,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 14,
          y: 6,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 14,
          y: 8,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 4,
          y: 8,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 4,
          y: 6,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 0,
          y: 8,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 0,
          y: 6,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 18,
          y: 6,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 18,
          y: 8,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 10,
          y: 3,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 8,
          y: 3,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 8,
          y: 11,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 10,
          y: 11,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 10,
          y: 1,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 8,
          y: 1,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 15,
          y: 6,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 15,
          y: 8,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 3,
          y: 8,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 3,
          y: 6,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 8,
          y: 13,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 10,
          y: 13,
        },
      },
      {
        type: 'CITY',
        factionId: 'RED',
        position: {
          x: 1,
          y: 1,
        },
      },
      {
        type: 'CITY',
        factionId: 'BLUE',
        position: {
          x: 17,
          y: 1,
        },
      },
      {
        type: 'CITY',
        factionId: 'YELLOW',
        position: {
          x: 17,
          y: 13,
        },
      },
      {
        type: 'CITY',
        factionId: 'GREEN',
        position: {
          x: 1,
          y: 13,
        },
      },
      {
        type: 'BASE',
        factionId: 'RED',
        position: {
          x: 2,
          y: 1,
        },
      },
      {
        type: 'BASE',
        factionId: 'BLUE',
        position: {
          x: 16,
          y: 1,
        },
      },
      {
        type: 'BASE',
        factionId: 'YELLOW',
        position: {
          x: 16,
          y: 13,
        },
      },
      {
        type: 'BASE',
        factionId: 'GREEN',
        position: {
          x: 2,
          y: 13,
        },
      },
      {
        type: 'AIRPORT',
        factionId: 'RED',
        position: {
          x: 3,
          y: 1,
        },
      },
      {
        type: 'AIRPORT',
        factionId: 'BLUE',
        position: {
          x: 15,
          y: 1,
        },
      },
      {
        type: 'AIRPORT',
        factionId: 'YELLOW',
        position: {
          x: 15,
          y: 13,
        },
      },
      {
        type: 'AIRPORT',
        factionId: 'GREEN',
        position: {
          x: 3,
          y: 13,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 6,
          y: 5,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 6,
          y: 9,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 12,
          y: 9,
        },
      },
      {
        type: 'BASE',
        factionId: null,
        position: {
          x: 12,
          y: 5,
        },
      },
      {
        type: 'AIRPORT',
        factionId: null,
        position: {
          x: 9,
          y: 7,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 9,
          y: 6,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 8,
          y: 7,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 10,
          y: 7,
        },
      },
      {
        type: 'CITY',
        factionId: null,
        position: {
          x: 9,
          y: 8,
        },
      },
    ],
    units: [],
    name: 'Town mayhem',
    description: "Let's capture.",
  }
}

export default townMayhem
