function ambush() {
  return {
    worldMap: [
      [
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
      ],
      [
        'SEA',
        'HEADQUARTERS',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'SEA',
      ],
      [
        'SEA',
        'RIVER',
        'RIVER',
        'RIVER',
        'PLAIN',
        'ROAD',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'HEADQUARTERS',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'ROAD',
        'RIVER',
        'RIVER',
        'RIVER',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'RIVER',
        'RIVER',
        'RIVER',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'RIVER',
        'RIVER',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'RIVER',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'ROAD',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'PLAIN',
        'SEA',
      ],
      [
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
        'SEA',
      ],
    ],
    factions: [
      {
        id: 'RED',
        type: 'HUMAN',
        team: 1,
      },
      {
        id: 'BLUE',
        type: 'COMPUTER',
        team: 2,
      },
    ],
    buildings: [
      {
        type: 'HEADQUARTERS',
        factionId: 'RED',
        position: {
          x: 1,
          y: 1,
        },
      },
      {
        type: 'HEADQUARTERS',
        factionId: 'BLUE',
        position: {
          x: 18,
          y: 7,
        },
      },
    ],
    units: [
      {
        id: '0b03c539-db22-4721-946f-19424a667f9e',
        type: 'INFANTERY',
        factionId: 'RED',
        position: {
          x: 3,
          y: 2,
        },
      },
      {
        id: '6068f634-a350-46d1-ac3b-ddf5ed684be8',
        type: 'INFANTERY',
        factionId: 'RED',
        position: {
          x: 3,
          y: 3,
        },
      },
      {
        id: '9d70fb96-4bf7-4f62-8911-1b29336eea1f',
        type: 'INFANTERY',
        factionId: 'RED',
        position: {
          x: 3,
          y: 9,
        },
      },
      {
        id: '3753b3d0-bd4d-4691-a046-6e41b4ef2561',
        type: 'INFANTERY',
        factionId: 'RED',
        position: {
          x: 3,
          y: 10,
        },
      },
      {
        id: '69842f94-04bb-433b-8c1b-f57914c8ded9',
        type: 'TANK',
        factionId: 'RED',
        position: {
          x: 2,
          y: 2,
        },
      },
      {
        id: 'dee238f7-00c2-46f0-b790-b8383b8057d9',
        type: 'TANK',
        factionId: 'RED',
        position: {
          x: 2,
          y: 3,
        },
      },
      {
        id: 'e22fea8c-f5f3-47e4-ba8c-8bda10c298c3',
        type: 'TANK',
        factionId: 'RED',
        position: {
          x: 2,
          y: 9,
        },
      },
      {
        id: '8e6e16d0-4e29-4105-9d3b-153da4576c25',
        type: 'TANK',
        factionId: 'RED',
        position: {
          x: 2,
          y: 10,
        },
      },
      {
        id: '5ee7fee6-855f-4815-8291-42b269bdbdeb',
        type: 'ARTILLERY',
        factionId: 'RED',
        position: {
          x: 2,
          y: 4,
        },
      },
      {
        id: 'd954712a-6f1b-49cd-b3a6-38a623a544eb',
        type: 'ARTILLERY',
        factionId: 'RED',
        position: {
          x: 2,
          y: 11,
        },
      },
      {
        id: '41aaeec8-8532-4215-8a8f-ac14c04dfddb',
        type: 'HEAVY_TANK',
        factionId: 'RED',
        position: {
          x: 1,
          y: 2,
        },
      },
      {
        id: 'ddb39a9e-9547-4eb5-8408-32a2851898b5',
        type: 'HEAVY_TANK',
        factionId: 'RED',
        position: {
          x: 1,
          y: 9,
        },
      },
      {
        id: 'd57994e7-4efd-4336-9c1b-88ea8820d273',
        type: 'MECH',
        factionId: 'RED',
        position: {
          x: 4,
          y: 2,
        },
      },
      {
        id: '523c6406-6808-45e2-a5a8-a9cdc5435e56',
        type: 'MECH',
        factionId: 'RED',
        position: {
          x: 4,
          y: 9,
        },
      },
      {
        id: '30d7bec2-bb05-4453-8e8f-3a326d5d1345',
        type: 'INFANTERY',
        factionId: 'BLUE',
        position: {
          x: 16,
          y: 6,
        },
        flipped: true,
      },
      {
        id: 'e5ce47d1-5da6-48c3-8107-577f8573b341',
        type: 'INFANTERY',
        factionId: 'BLUE',
        position: {
          x: 16,
          y: 5,
        },
        flipped: true,
      },
      {
        id: '382fe25e-7ab7-4c84-92b9-f63da080d320',
        type: 'INFANTERY',
        factionId: 'BLUE',
        position: {
          x: 11,
          y: 11,
        },
        flipped: true,
      },
      {
        id: '43b29d04-ba25-4c00-bfda-20adcf31b454',
        type: 'INFANTERY',
        factionId: 'BLUE',
        position: {
          x: 10,
          y: 11,
        },
        flipped: true,
      },
      {
        id: '41347fb5-a5a7-4709-aae0-b23433defcbf',
        type: 'MECH',
        factionId: 'BLUE',
        position: {
          x: 15,
          y: 6,
        },
        flipped: true,
      },
      {
        id: '29398f4f-67e7-4b2d-b33d-ba05b737abef',
        type: 'MECH',
        factionId: 'BLUE',
        position: {
          x: 10,
          y: 10,
        },
        flipped: true,
      },
      {
        id: '4961b163-e3a6-4c8b-917b-3f7cf6c08a04',
        type: 'TANK',
        factionId: 'BLUE',
        position: {
          x: 10,
          y: 12,
        },
        flipped: true,
      },
      {
        id: 'eb0ae2ed-deb9-43d5-b774-9ad1f1ee8d53',
        type: 'TANK',
        factionId: 'BLUE',
        position: {
          x: 11,
          y: 12,
        },
        flipped: true,
      },
      {
        id: 'a950e62b-2da4-4ab2-877e-964a15aa783c',
        type: 'TANK',
        factionId: 'BLUE',
        position: {
          x: 17,
          y: 6,
        },
        flipped: true,
      },
      {
        id: 'c8539ebf-c502-4909-974a-99f4e324cfa3',
        type: 'TANK',
        factionId: 'BLUE',
        position: {
          x: 17,
          y: 5,
        },
        flipped: true,
      },
      {
        id: '91b81d8a-4ad2-4c48-a50a-4d95cf590220',
        type: 'ARTILLERY',
        factionId: 'BLUE',
        position: {
          x: 17,
          y: 4,
        },
        flipped: true,
      },
      {
        id: 'f96263d7-85f8-4656-aa4d-ca2801f3f0fe',
        type: 'ARTILLERY',
        factionId: 'BLUE',
        position: {
          x: 12,
          y: 12,
        },
        flipped: true,
      },
      {
        id: 'f74c798c-1d86-4856-8ec5-0703c8179a98',
        type: 'HEAVY_TANK',
        factionId: 'BLUE',
        position: {
          x: 18,
          y: 6,
        },
        flipped: true,
      },
      {
        id: '16863c41-54a8-4343-b828-4be62d052f8b',
        type: 'HEAVY_TANK',
        factionId: 'BLUE',
        position: {
          x: 10,
          y: 13,
        },
        flipped: true,
      },
    ],
    name: 'Ambush',
    description: 'Get out of there, quick!',
  }
}

export default ambush
